#
* *MuHitDisplay* : STNTUPLE event display                                    
** how to run                                                                
#+begin_src
mu2e -c Stntuple/fcl/display.fcl -s dig.mu2e.CeEndpointDigiTriggered.MDC2020n_10pc.001210_00000000.art 
#+end_src
** event display module                                                      
   - source code : [[file:../mod/MuHitDisplay_module.cc]] 
   - FCL defaults: [[file:../fcl/prolog.fcl::/module_type:MuHitDisplay/]]

   TStnVisManager-specific settings: file:../fcl/prolog.fcl::/visManager/

   - visManager.defaultView : view opened in the first window, "xy", "vst", etc
     - default: "xy"

   - visManager.displayStrawDigiMC
   - visManager.bField      : used to display trajectories in the tracker,
                              default = 1.0 (in Tesla)
   - visManager.debugLevel  : debugging optioin, default = 0

** Object colors, legends
*** XY, TZ and PZ views:
   - Combo Hit colors are defined by PDG ID in [[file:../gui/TEvdComboHit.cc::79]] (around line 79)
   - Straw Hit colors are defined together by PDG ID in file:../gui/TTrkVisNode.cc::272 (around line 272)
   - Sim Particle colors are defined by PDG ID in file:../gui/TEvdSimParticle.cc::97 (around line 97)
   - For these objects:
|-----------+-----------------|
| color     | meaning         |
|-----------+-----------------|
| kRed      | e- P>20 MeV/c   |
| kRed+2    | e- P<20 MeV/c   |
|-----------+-----------------|
| kBlue     | positrons       |
| kBlue+2   | protons         |
| kGreen+2  | muons           |
| kGreen-2  | antimuons       |
| kOrange-3 | +ve pions       |
| kOrange+7 | -ve pions       |
| kBlack    | everything else |
|-----------+-----------------|

   - Helices are depicted as a dash-dot line, and are always kGreen+4, as in file:../gui/TEvdHelixSeed.cc::75 (around line 75)
   - Tracks are always kViolet, as in file:../gui/TEvdTrack.cc::135 (around line 135)  
   - In XY view, Calorimeter clusters are depicted as red (disk 1) and magenta (disk 2) translucent circles
   - This information can be viewed in Open -> Legend XY
   - Functionality exists in TTrkVisNode only to support in-time versus out-of-time electrons, with out-of-time
     being  kAzure+1. Since this is the only file with this functionality, the line is commented out as of this update.
*** Cal view:
   - In the calorimeter view:
|-----------+-----------------------------|
| color     | meaning                     |
|-----------+-----------------------------|
| kRed+2    | Hit in a cluster            |
|           | >100 MeV/c                  |
| kRed      | Hit in a cluster            |
|           | >10 MeV/c                   |
| kRed-9    | Hit in a cluster            |
|           | >1 MeV/c                    |
| kRed-10   | Hit in a cluster            |
|           | <1 MeV/c                    |
| kYellow-7 | Hit exceeding minimum       |
|           | threshold energy, but       |
|           | not part of any cluster     |
| No color  | No hit of sufficient energy |
|           | recorded in crystal         |
|           |                             |
|-----------+-----------------------------|
   - This information can be viewed in Open -> Legend Cal
   - Cluster energy colors are defined in file:../gui/TCalVisNode.cc::137 (around line 137)
*** Cal view:
   - In crv view, the color is a gradient of time of hit since start of timing
   - Colors range from blue (earliest) to red (latest)
   - There exists a slider which should set the time window and fit the color
     gradient to this window. However (as of this update) the slider does not appear in the current
     gui. The code for the slider exists in file:../gui/TStnVisManager.cc::165 (around line 165)
   - A legend which uses the default timeframe (400-1695 ns) can be accessed with Open -> Legend CRV

All legends are defined as functions and used in file:../gui/TStnFrame.cc, and should be manually changed
if color or style changes are made to the event displays to keep them relevant (last updated 07/21/2025).
Adding new legends will also require minor edits in  file:../gui/gui/TStnFrame.hh and file:../gui/gui/TStnWidgetID.hh
     


** interactive commands                                                      

  - process next event: type ".q" at the ROOT prompt

  - exit: type .qqqqqq at the ROOT prompt
           
  - right-click on an object pops-up the object's context-sensitive menu

  - Left, Right, Up, and Down arrow keys move the scene

  - mouse weel (Up, and Down) changes the scale

  - left-click pops up a ROOT context-sensitive menu, which depends 
    on the closest to the cursor object 

  - left-click on a time cluster (TZ view) selects the time cluster.
    when a time cluster is selected, displayed in all views are only 
    tracks , hits and such with times within the selected time cluster

** display of SimParticles                                                   
   - if *primaryParticleTag* is set to an empty string, 
     all particles with E>Emin and hits in the straw tracker will be saved
     and displayed
   - if, however, *primaryParticleTag* is set not non-empty string, 
     saved in STNTUPLE and displayed will be only particles pre-selected 
     from that list , still with N(straw hits) > 0 and E > Emin
** plugin macros                                                             
  -  MuHitDisplay can execute ROOT scripts in an interpreted mode.
  - the following FCL parameter of a STNTUPLE module (any module class inheriting from TModule)

#+begin_src
   interactiveMode : 2
   rootMacro       : "Stntuple/mod/scripts/display_001.C"
#+end_src

     makes the module to execute a function "display_001(int Mode, TModule* Module)" 
     each time MuHitDisplay is called 

   - the same is true for any module inheriting from [[file:../mod/TModule.cc][Stntuple/mod/TModule.cc]], assuming the module calls proper 
     TModule hooks. Search the source of [[file:../mod/MuHitDisplay_module.cc][Stntuple/mod/MuHitDisplay_module.cc]] for "TModule"

   see example: [[file:../mod/scripts/display_001.C][Stntuple/mod/scripts/display_001.C]] 
#+begin_src
   Parameters
   ----------
   Mode = 0: begin job (run)
        = 1: event
        = 2: end job (run)

   Module  : pointer to the calling module, if the module dictionary exists, could call its functions

   interactiveMode = 1 : stop at a ROOT prompt after processing each event
                   = 2 : stop only in the end of run
#+end_src
    
** views                                                                     
  - display supports multiple views. Currently available are:
    - XY view   : tracker+calorimeter
    - TZ view   : tracker hits, time clusters, MC particles
    - PhiZ view : tracker hits
    - Cal view  : clusters, hits in individual crystals
    - CRV view  : 
    - RZ view   : tracker hits 
    - VST view  : tracker VST geometry
  - by default, a view prints a list of all its nodes
** printing                                                                  
- prints : under the "print" section of the shutter
- right click on a view pops up a context sensitive menu, a TStnView print prints 
  all nodes (objects) displayed in the active view
- "Print Canvas as PNG" creates n output of the open view in the home folder as "output.png".
  This functionality is in file:../gui/TStnFrame.cc 

** quick notes about internals                                               
  - Several views : derived from TStnView - XYView, RZView, TZView
  - each view displays geometry and several nodes 
  - a node controls interactive cbehavior - DistanceToPrimitive
  - each note "knows" how to paint itself in each view PaintXY, PaintRZ, etc 
  - 3D views: need a simplified geometry, work in progress 
** printing in interactive mode                                              
- see [[file:../print/print/Stntuple_print_functions.hh][Stntuple/print/print/Stntuple_print_functions.hh]] for the list of functions which could be called
- contribute if you need more! 
#+begin_quote   print time cluster collection                                
   d = TAnaDump::Instance()
   d->printTimeClusterCollection("TZClusterFinder","makePH","DeltaFinder::ComboHits",1,"makeSD")    
#+end_quote               

  - print available collection names :

#+begin_quote
  print_ch_colls()
  print_genp_colls()
  print_combo_hit_colls()
  print_helix_seed_colls()
  print_kalseed_colls()
  print_kalrep_colls()           ; // obsolete
  print_sd_colls()
  print_shf_colls()
  print_simp_colls()
  print_spmc_solls()
  print_tc_colls()
#+end_quote
** known issues                                                              
*** window is not updating while everything else seems to function OK        
    - move the cursor out of the window and then back in. Scroll the mouse wheel up and down
* ------------------------------------------------------------------------------
* [1/1] TODO's                                                               
** DONE add a SimParticle node ? or just add a list of SimParticles to XY view ?
   added a list of SimParticles to TStnTrackNode
* ------------------------------------------------------------------------------
